### ISSUE TITLE
Setup testing:

### ISSUE THREAD

**Issue by Reificator** [Reificator/ecs-arcade#7]
- [x] Determine which testing framework to use [Mocha + Chai]
- [x] Install testing framework
- [x] Figure out how to put tests inline and automatically run `**/*.test.js` test files
- [x] Figure out how to run tests and tested code in ES6, including `import` and `export`
- [x] Track down problem with importing mocha [ No reason to import mocha, it gets loaded into global scope]
- [x] Now that we have a working test, start again from a clean slate so we have just enough to run ES6 import tests from side-by-side
- [x] Exclude node_modules from webpack/babel when testing
- [x] Setup local testing
- [x] Setup Travis to run tests
- [x] Evaluate https://codecov.io

**Comment by Reificator** [comment]
When importing mocha with webpack we get the following errors:

```
WARNING in ./~/mocha/lib/mocha.js
153:20-37 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/mnt/d/ecs-arcade/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:663:24)
    at Compilation.finish (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:526:9)
    at /mnt/d/ecs-arcade/node_modules/webpack/lib/Compiler.js:472:16
    at /mnt/d/ecs-arcade/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:472:11)
    at processModuleDependencies.err (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:443:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./~/mocha/lib/mocha.js
185:17-30 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/mnt/d/ecs-arcade/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:663:24)
    at Compilation.finish (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:526:9)
    at /mnt/d/ecs-arcade/node_modules/webpack/lib/Compiler.js:472:16
    at /mnt/d/ecs-arcade/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:472:11)
    at processModuleDependencies.err (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:443:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

WARNING in ./~/mocha/lib/mocha.js
222:26-39 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/mnt/d/ecs-arcade/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:663:24)
    at Compilation.finish (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:526:9)
    at /mnt/d/ecs-arcade/node_modules/webpack/lib/Compiler.js:472:16
    at /mnt/d/ecs-arcade/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:472:11)
    at processModuleDependencies.err (/mnt/d/ecs-arcade/node_modules/webpack/lib/Compilation.js:443:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

ERROR in ./~/growl/lib/growl.js
Module not found: Error: Can't resolve 'child_process' in '/mnt/d/ecs-arcade/node_modules/growl/lib'
resolve 'child_process' in '/mnt/d/ecs-arcade/node_modules/growl/lib'
  Parsed request is a module
  using description file: /mnt/d/ecs-arcade/node_modules/growl/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /mnt/d/ecs-arcade/node_modules/growl/package.json (relative path: ./lib)
    resolve as module
      /mnt/d/ecs-arcade/node_modules/node_modules doesn't exist or is not a directory
      /mnt/d/node_modules doesn't exist or is not a directory
      /mnt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /mnt/d/ecs-arcade/node_modules/growl/lib/node_modules doesn't exist or is not a directory
      /mnt/d/ecs-arcade/node_modules/growl/node_modules doesn't exist or is not a directory
      looking for modules in /mnt/d/ecs-arcade/node_modules
        using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules)
          using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules/child_process)
            as directory
              /mnt/d/ecs-arcade/node_modules/child_process doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/child_process doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/child_process.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/child_process.json doesn't exist
[/mnt/d/ecs-arcade/node_modules/node_modules]
[/mnt/d/node_modules]
[/mnt/node_modules]
[/node_modules]
[/mnt/d/ecs-arcade/node_modules/growl/lib/node_modules]
[/mnt/d/ecs-arcade/node_modules/growl/node_modules]
[/mnt/d/ecs-arcade/node_modules/child_process]
[/mnt/d/ecs-arcade/node_modules/child_process]
[/mnt/d/ecs-arcade/node_modules/child_process.js]
[/mnt/d/ecs-arcade/node_modules/child_process.json]
 @ ./~/growl/lib/growl.js 7:11-35
 @ ./~/mocha/lib/mocha.js
 @ ./~/mocha/browser-entry.js
 @ ./src/modules/core/systems/Velocity.test.js
 @ ./src object Object
 @ ./.tmp/mocha-webpack/7072522f547a4ba30a695640f510fede-entry.js

ERROR in ./~/growl/lib/growl.js
Module not found: Error: Can't resolve 'fs' in '/mnt/d/ecs-arcade/node_modules/growl/lib'
resolve 'fs' in '/mnt/d/ecs-arcade/node_modules/growl/lib'
  Parsed request is a module
  using description file: /mnt/d/ecs-arcade/node_modules/growl/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /mnt/d/ecs-arcade/node_modules/growl/package.json (relative path: ./lib)
    resolve as module
      /mnt/d/ecs-arcade/node_modules/node_modules doesn't exist or is not a directory
      /mnt/d/node_modules doesn't exist or is not a directory
      /mnt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /mnt/d/ecs-arcade/node_modules/growl/lib/node_modules doesn't exist or is not a directory
      /mnt/d/ecs-arcade/node_modules/growl/node_modules doesn't exist or is not a directory
      looking for modules in /mnt/d/ecs-arcade/node_modules
        using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules)
          using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules/fs)
            as directory
              /mnt/d/ecs-arcade/node_modules/fs doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/fs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/fs.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/fs.json doesn't exist
[/mnt/d/ecs-arcade/node_modules/node_modules]
[/mnt/d/node_modules]
[/mnt/node_modules]
[/node_modules]
[/mnt/d/ecs-arcade/node_modules/growl/lib/node_modules]
[/mnt/d/ecs-arcade/node_modules/growl/node_modules]
[/mnt/d/ecs-arcade/node_modules/fs]
[/mnt/d/ecs-arcade/node_modules/fs]
[/mnt/d/ecs-arcade/node_modules/fs.js]
[/mnt/d/ecs-arcade/node_modules/fs.json]
 @ ./~/growl/lib/growl.js 8:9-22
 @ ./~/mocha/lib/mocha.js
 @ ./~/mocha/browser-entry.js
 @ ./src/modules/core/systems/Velocity.test.js
 @ ./src object Object
 @ ./.tmp/mocha-webpack/7072522f547a4ba30a695640f510fede-entry.js

ERROR in ./~/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in '/mnt/d/ecs-arcade/node_modules/mkdirp'
resolve 'fs' in '/mnt/d/ecs-arcade/node_modules/mkdirp'
  Parsed request is a module
  using description file: /mnt/d/ecs-arcade/node_modules/mkdirp/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /mnt/d/ecs-arcade/node_modules/mkdirp/package.json (relative path: .)
    resolve as module
      /mnt/d/ecs-arcade/node_modules/node_modules doesn't exist or is not a directory
      /mnt/d/node_modules doesn't exist or is not a directory
      /mnt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /mnt/d/ecs-arcade/node_modules
        using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules)
          using description file: /mnt/d/ecs-arcade/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/fs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/fs.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /mnt/d/ecs-arcade/node_modules/fs.json doesn't exist
            as directory
              /mnt/d/ecs-arcade/node_modules/fs doesn't exist
      /mnt/d/ecs-arcade/node_modules/mkdirp/node_modules doesn't exist or is not a directory
[/mnt/d/ecs-arcade/node_modules/node_modules]
[/mnt/d/node_modules]
[/mnt/node_modules]
[/node_modules]
[/mnt/d/ecs-arcade/node_modules/fs]
[/mnt/d/ecs-arcade/node_modules/fs.js]
[/mnt/d/ecs-arcade/node_modules/fs.json]
[/mnt/d/ecs-arcade/node_modules/fs]
[/mnt/d/ecs-arcade/node_modules/mkdirp/node_modules]
 @ ./~/mkdirp/index.js 2:9-22
 @ ./~/mocha/lib/reporters/xunit.js
 @ ./~/mocha/lib/reporters/index.js
 @ ./~/mocha/lib/mocha.js
 @ ./~/mocha/browser-entry.js
 @ ./src/modules/core/systems/Velocity.test.js
 @ ./src object Object
 @ ./.tmp/mocha-webpack/7072522f547a4ba30a695640f510fede-entry.js
```

**Comment by Reificator** [comment]
Oh of course, Mocha gets loaded into global scope anyway, so who cares if it imports things dynamically.  We don't need to actually import it with webpack in the first place

**Comment by Reificator** [comment]
Getting codecov.io working is going to require us getting istanbul working, which will be interesting with our webpack + babel setup.  Adding another card for that project and closing this issue.

**Comment by Reificator** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setup testing](https://trello.com/c/d6PIEGNu/8-setup-testing)
